name: Deploy Firebase Rules

on:
  push:
    branches: [ main ]
    paths:
      - 'firestore.rules'
      - '.firebaserc'
      - 'firebase.json'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy Firebase Rules
        uses: w9jds/firebase-action@v14.19.1
        with:
          args: deploy --only firestore:rules
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
